### ISSUE TITLE
Add support for ethers 6

### ISSUE THREAD

**Issue by ifavo** [vechain/web3-providers-connex#23]
Given a project using ethers 6
When web3-providers-connex is added
Then it will fail due import failures for ethers/lib/utils

- web3-providers-connex has a peerDepencency to ethers v5 but v6 was released early this year.
- I have not search for the exact reason, but from a quick search I imagine this to be the relevant part, due moving access to the utils part at ethers: https://github.com/vechain/web3-providers-connex/blob/70ba1c49b5b478ed7c53e5abf82777ae25c7f282/src/ethers.ts#L20-L29

Reproduction example would be:

```shell
yarn add ethers @vechain/web3-providers-connex
```

```js
import * as thor from '@vechain/web3-providers-connex'
import { ethers } from "ethers";

const connex = new Connex({
  node: "https://node-mainnet.vechain.energy",
  network: "main"
});

const provider = thor.ethers.modifyProvider(
  new ethers.providers.Web3Provider(
    new thor.Provider({ connex })
  )
)
```

**Comment by zzGHzz** [comment]
I've checked ethers 6 and there wouldn't be a quick fix for ethers 6.

**Comment by zzGHzz** [comment]
Check out branch ethers6 to be able to use ethers v6

**Comment by ifavo** [comment]
Awesome! Will give it a try, thank you!
