### ISSUE TITLE
Modifired ethers provider doesn't work.

### ISSUE THREAD

**Issue by devlancer412** [vechain/web3-providers-connex#30]
I tried to use ethers provider with this module.
![image](https://github.com/vechain/web3-providers-connex/assets/101313445/5a52d5c5-3975-487c-b16a-2758b03c3b46)

And tried to get balance. but it occurs error.
![image](https://github.com/vechain/web3-providers-connex/assets/101313445/eb7e11f9-4d72-4f17-b068-ba86ef60467e)

![image](https://github.com/vechain/web3-providers-connex/assets/101313445/bb2d11d0-6143-4424-9b75-e855070b5a35)

**Comment by zzGHzz** [comment]
Please check the latest release v1.1.0
