### ISSUE TITLE
Latest npm version (1.1.0) fails to build correctly when used as a dependency

### ISSUE THREAD

**Issue by MakisChristou** [vechain/web3-providers-connex#36]
I am in the process of upgrading [hardhat-plugins](https://github.com/vechainfoundation/hardhat-plugins) and [hardhat-plugin-sample-ethers](https://github.com/vechainfoundation/hardhat-plugin-sample-ethers) to use web3-providers-connex that supports ethersv6 instead of v5. I made some modifications locally in both of those projects to facilitate that change and have been using a local version of web3-providers-connex version 1.1.0 which worked and I could run and pass all the tests in hardhat-plugin-sample-ethers. The issue is when using the recently published npm version instead of a locally built one. It seems as if the npm version is not being built correctly and that most node_modules are missing after running `yarn install` and `yarn build` in the hardhat-plugin repository. The specific error that I am getting in the sample project after running `npx hardhat compile` is `Error: Cannot find module '../node_modules/ethers/lib.commonjs/providers/format'` which indeed is not there. Actually in the sample project the folder `node_modules/@vechain/web3-providers-connex` contains only the following:

- LICENSE
- package.json
- README.md

Please let me know if I am missing something or if its indeed an issue with the npm package.

**Comment by zzGHzz** [comment]
fixed
