### ISSUE TITLE
LogIndex and TransactionIndex of events are always 0

### ISSUE THREAD

**Issue by andreas-papageorgiou** [vechain/web3-providers-connex#9]
Transaction and log indices, contained in logs and receipts can be used to check transaction & event orders, and generally enhance audit ability.

When formatted, these are always set to 0:
https://github.com/vechain/web3-providers-connex/blob/e4fc5fd8a4713b475453d2ced217e1ecc3cdebee/src/formatter.ts#L249-L250
https://github.com/vechain/web3-providers-connex/blob/e4fc5fd8a4713b475453d2ced217e1ecc3cdebee/src/formatter.ts#L329-L330

Since it is possible (but more expensive) to obtain them, we suggest to add flags to the `Formatter` and `Provider`'s constructors, e.g.:
- `includeLogIndex`
- `includeTxIndex`

to allow users to opt-in to this information, by fetching it while formatting, only these flags are set.

**Comment by zzGHzz** [comment]
code updated for enabling logIndex and transactionIndex
